---
- name: Pull docker image from ECR
  hosts: all
  become: yes

  tasks:
  - name: Ping servers
    ping:

  - name: login
    ansible.builtin.shell:
      cmd: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 996548385171.dkr.ecr.eu-central-1.amazonaws.com

  - name: Pull
    ansible.builtin.shell:
      cmd: docker pull 996548385171.dkr.ecr.eu-central-1.amazonaws.com/sample-rails-app:{{ build_number }}
  
  - name: Stop container
    ansible.builtin.shell:
      cmd: docker stop rails-app || exit 0 

  - name: Start container
    ansible.builtin.shell:
      cmd: docker run --name=rails-app -d --publish 80:3000 996548385171.dkr.ecr.eu-central-1.amazonaws.com/sample-rails-app:{{ build_number }}
