---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: install docker
  yum:
    name='docker'
    state=latest

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure Python pip packages are installed
  pip:
    name:
      - docker


- name: Init docker swarm
  ansible.builtin.shell:
    cmd: docker swarm init
