---
- name: configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- include_tasks: docker_install.yml

- name: login
  ansible.builtin.shell:
    cmd: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 996548385171.dkr.ecr.eu-central-1.amazonaws.com

- name: Pull
  ansible.builtin.shell:
    cmd: docker pull 996548385171.dkr.ecr.eu-central-1.amazonaws.com/sample-rails-app:{{ build_number }}

- name: Start container
  ansible.builtin.shell:
    cmd: BUILD_NUMBER={{ build_number }} docker stack deploy rails-app --compose-file docker_compose.yml