---
- name: Install prerequisites
  yum: name=python-software-properties state=present
  become: true

- name: Add deadsnakes repo
  yum_repository: repo="ppa:deadsnakes/ppa"
  become: true

- name: Install python
  yum: name="python{{ python_version }}-dev" state=present
  become: true